### ISSUE TITLE
How to reduce the distance between rows?

### ISSUE THREAD

**Issue by it19862** [ckeditor/ckeditor5-basic-styles#69]
How to reduce the distance between rows?
![3142](https://user-images.githubusercontent.com/18245828/38550774-0ea18872-3cc0-11e8-92d2-5f54efa85640.jpg)

**Comment by Reinmar** [comment]
The layout of the editor content is controlled by CSS. So you can just remove any padding and margin between `<p>` and other block elements;

```css
.ck-content p, .ck-content h1, .ck-content h2, .ck-content h3 {
margin: 0;
padding: 0;
}
```
